import {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

interface HomePageProps {
  userAgent: string
}

const HomePage: NextPage<HomePageProps> = ({userAgent}) => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <h1>
        User agent is {userAgent}
      </h1>

    </div>
  )
}


export default HomePage


HomePage.getInitialProps = async ({req}) => {
  const userAgent = (req ? req.headers['user-agent'] : navigator.userAgent) as string
  return {userAgent}
}

// export const getStaticProps: GetStaticProps<HomePageProps> = (context) => {
//   return {
//     props: {
//       userAgent: '999'
//     }
//   }
// }

